import type { Lang } from "@/lib/lang";

type Dict = Record<string, string>;

export const ui: { fr: Dict; ar: Dict } = {
  fr: {
    "addToCart": "Ajouter au panier",
    "cart": "Panier",
    "quantity": "Quantité :",
    "qtyLabel": "Quantité",
    "total": "Total",
    "subtotal": "Sous-total",
    "free": "Gratuit",
    "freeShipping": "Livraison gratuite",
    "save": "Économisez",
    "youSave": "Vous économisez",
    "new": "Nouveau",
    "bestseller": "Bestseller",
    "reviews": "avis",
    "outOfStock": "Rupture",
    "inStock": "En stock",
    "from": "Dès",
    "trust": "Confiance",
    "guarantee": "Garantie 4 semaines",
    "delivery": "Livraison",
    "paymentCOD": "Paiement à la livraison",
    "contactUs": "Nous contacter",
    "allProducts": "Voir tous les produits",
    "ourProducts": "Nos Produits",
    "ourStory": "Notre Histoire",
    "returns": "Politique de retour",
    "tracking": "Suivi commande",
    "shippingCOD": "Livraison & COD",
    "conditions": "Conditions d'utilisation",
    "privacy": "Politique de confidentialité",
    "menu": "Menu",
    "close": "Fermer",
    "cartAria": "Panier",
    "continueShopping": "Continuer mes achats",
    "remove": "Retirer",

    "nav.notreHistoire": "Notre Histoire",
    "nav.products": "Nos Produits",
    "nav.velvastretch": "VelvaStretch™",
    "nav.silkstop": "SilkStop™",
    "nav.collaglow": "CollaGlow™",
    "nav.kit": "Kit Collagène Inside & Outside",
    "nav.contact": "Nous contacter",
    "nav.whatsapp": "WhatsApp",
    "nav.email": "Email",
    "nav.instagram": "Instagram",
    "nav.tiktok": "TikTok",
    "nav.retour": "Politique de retour",
    "nav.suivi": "Suivi commande",
    "nav.livraison": "Livraison",
    "nav.conditions": "Conditions d'utilisation",

    "announcement": "🇲🇦 Marque marocaine · 💳 Paiement à la livraison · 🚚 Livraison 24–48h",
    "announce.1": "🚚 Livraison gratuite partout au Maroc — Paiement à la livraison",
    "announce.2": "🌹 Fabriqué au Maroc | 100% naturel | résultats garantis",
    "announce.3": "⭐ +2 400 femmes marocaines satisfaites ce mois-ci",
    "tb.natural": "100% Ingrédients Naturels",
    "tb.madein": "Fabriqué au Maroc",
    "tb.cod": "Paiement à la livraison",
    "tb.derma": "Testé Dermatologiquement",
    "tb.ship": "Livraison 24–48h",

    "pp.whyLove": "Pourquoi tu vas l'aimer",
    "pp.science": "La science",
    "pp.ingredients": "Les ingrédients",
    "pp.howTo": "Comment utiliser",
    "pp.steps": "En 5 étapes",
    "pp.forYouIf": "Pour toi si :",
    "pp.testimonials": "Elles témoignent",
    "pp.moreResults": "Encore plus de résultats",
    "pp.alsoBought": "Les femmes qui ont pris {name} ont aussi pris",
    "pp.faq": "Questions fréquentes",
    "pp.viewInci": "Voir la liste INCI complète",
    "pp.comparisonTitle": "Pourquoi nous, et pas l'autre option ?",
    "pp.ceLabel": "Ce que ça fait",

    "kit.problemTitle": "Tu connais cette sensation, n'est-ce pas ?",
    "kit.problemBody": "Celle de cacher ton ventre au hammam. De ranger les robes courtes d'été. De détourner les yeux devant le miroir après la grossesse. Les vergetures, la peau qui a perdu sa fermeté… tu as essayé les huiles, les crèmes, les séances de laser. Et tu as attendu.",
    "kit.problemMicro": "Tu as tout essayé, et le résultat ? Rien.",
    "kit.scienceEyebrow": "La science, pas le marketing",
    "kit.scienceTitle": "Pourquoi ça marche enfin",
    "kit.sci1": "À 25 ans, ton corps produit 1% de collagène en moins chaque année. À 35, la fermeté fuit. Les crèmes classiques restent en surface — elles ne peuvent pas reconstruire ce qui se fabrique à l'intérieur.",
    "kit.sci2": "C'est pour ça qu'un seul produit ne suffit pas. Il faut attaquer sur les deux fronts :",
    "kit.sci3": "La recherche est claire : agir de l'intérieur et de l'extérieur en même temps donne plus que la somme des deux. Une méta-analyse de 26 études contrôlées (1 721 femmes) confirme l'amélioration nette de l'hydratation et de l'élasticité.",
    "kit.synergy": "Étude double-aveugle, femmes 45–54 ans : jusqu'à −31% de rides, +23% d'élasticité, +25% de fermeté en 12 semaines (vs placebo).",
    "kit.authorityTitle": "Pourquoi tu peux nous faire confiance",
    "kit.benefitsTitle": "Ce que tu vas voir",
    "kit.socialTitle": "Elles ont dit oui au duo",
    "kit.ritualEyebrow": "Comment l'utiliser",
    "kit.ritualTitle": "Le rituel en 2 gestes",
    "kit.ritualNote": "En 4 semaines, tu vois. En 12 semaines, tu ne te caches plus. 🌹",
    "kit.faqTitle": "Questions fréquentes",
    "kit.riskTitle": "Zéro risque. Vraie confiance.",
    "kit.riskBody": "Paiement à la livraison — tu ne payes que quand le colis arrive. Et si tu n'es pas convaincue en 4 semaines, on rembourse, sans discussion.",
    "kit.finalTitle": "Le Kit Collagène Inside & Outside",
    "kit.finalSub": "Les deux fronts, pour le prix d'un seul produit presque.",
    "kit.viewAll": "Voir tous les produits",
    "kit.save": "Vous économisez",
    "kit.badge1": "🇲🇦 Fabriqué au Maroc",
    "kit.badge2": "🧪 Testé dermatologiquement",
    "kit.badge3": "🌿 Halal & Vegan",
    "kit.badge4": "🚫 Sans paraben / sulfate",
    "kit.badge5": "🔬 Formulé au labo de Casablanca",
    "kit.badge6": "↩️ Garantie 4 semaines",
    "kit.urgency": "⚡ Offre limitée — stocks réduits",
    "kit.extTitle": "🩹 L'EXTÉRIEUR — VelvaStretch™",
    "kit.extBody": "Sérum au collagène marin hydrolysé qui pénètre 1,5× plus profondément que le collagène bovin, pour estomper les vergetures et redensifier la peau.",
    "kit.intTitle": "💊 L'INTÉRIEUR — CollaGlow™",
    "kit.intBody": "2 500 mg de collagène marin hydrolysé + acide hyaluronique + vitamine C + biotine, qui rebuild la peau, les cheveux et les ongles depuis la source.",
    "kit.insideEyebrow": "La formule",
    "kit.insideTitle": "Ce qu'il y a dans le kit",
    "kit.insideBody": "Deux produits complémentaires, une seule mission : reconstruire ta peau des deux côtés.",
    "kit.social1": "⭐ 4.9/5 sur 2 662 avis",
    "kit.social2": "🇲🇦 +12 000 clientes",
    "kit.social3": "🚚 94% livré en 48h",

    "as.title": "Pourquoi nos clientes nous font confiance",
    "as.sub": "Une marque marocaine, pensée pour la peau méditerranéenne.",
    "as.authorityTitle": "Formulé en toute sécurité",
    "as.authorityBody": "Formules testées sous contrôle dermatologique, sans parabènes ni sulfates. Pensées pour la peau méditerranéenne, même sensible. VelvaStretch™ est sans retinol — donc sûr pendant et après la grossesse.",
    "as.halalTitle": "Halal & Vegan certifié",
    "as.halalBody": "Collagène marin (poisson), base pectine végétale sans gélatine animale. Certifié halal & vegan — parce que pour vous, ce qui entre dans la peau compte autant que ce qui entre dans l'assiette.",
    "as.guaranteeTitle": "Garantie 4 semaines",
    "as.guaranteeBody": "Vous essayez, vous voyez. Si vous n'êtes pas convaincue après 4 semaines d'utilisation régulière, on rembourse — sans discussion, sans retour compliqué.",
    "as.codTitle": "Paiement à la livraison",
    "as.codBody": "Vous ne payez rien à l'avance. Le colis arrive chez vous en 24–48h partout au Maroc, et vous réglez seulement à la livraison. Zéro risque, zéro avance.",
    "as.codTrust": "Confiance d'abord",

    "cart.title": "Panier",
    "cart.empty": "Votre panier est vide",
    "cart.emptyCta": "Découvrir nos produits",
    "cart.youMayLike": "💡 Vous aimerez aussi (même prix d'origine) :",
    "cart.subtotal": "Sous-total",
    "cart.checkout": "Commander",
    "cart.freeShip": "Livraison gratuite incluse",

    "co.title": "Finaliser la commande",
    "co.name": "Nom complet",
    "co.namePh": "Ex : Samira Benali",
    "co.phone": "Téléphone",
    "co.phonePh": "06/07 XXXXXXXX",
    "co.address": "Adresse de livraison",
    "co.addressPh": "Rue, quartier, numéro…",
    "co.city": "Ville",
    "co.cityPh": "Casablanca",
    "co.notes": "Notes (optionnel)",
    "co.notesPh": "Point de repère, étage…",
    "co.cod": "Paiement à la livraison",
    "co.codNote": "Vous ne payez rien maintenant. Le livreur encaisse à la livraison.",
    "co.submit": "Confirmer la commande",
    "co.processing": "Traitement…",
    "co.summary": "Récapitulatif",
    "co.success": "Commande confirmée !",
    "co.successBody": "Merci ! Notre équipe vous appelle sous peu pour confirmer. Paiement à la livraison.",
    "co.error": "Une erreur est survenue. Réessayez.",
    "co.close": "Fermer",
    "co.nameReq": "Nom requis",
    "co.phoneReq": "Numéro marocain invalide. Ex: 0612345678 ou 0712345678",
    "co.cityReq": "Ville requise",
    "co.secure": "🔒 Vos données sont protégées · ⚡ 47 personnes regardent",
    "co.back": "Retour",
    "co.errorMorocco": "Désolé, les commandes sont réservées au Maroc 🇲🇦.",
    "co.errorPhone": "Numéro marocain invalide. Ex: 0612345678 ou 0712345678",
    "co.errorBlocked": "Accès non autorisé depuis ce réseau.",
    "co.errorGeneric": "Une erreur est survenue. Réessayez.",
    "co.upsellBody": "La beauté par l'intérieur + l'extérieur. Ensemble, ils valent 49 MAD de moins.",
    "co.upsellBoth": "Vous avez déjà le duo complet 🌹 — on vous offre −{discount} MAD sur votre commande.",
    "co.upsellSave": "Vous économisez {discount} MAD · expire dans {sec}s",
    "co.upsellAdd": "Ajouter {name} · −{discount} MAD",
    "co.upsellApply": "Appliquer −{discount} MAD",
    "co.upsellNo": "Non merci",

    "footer.badge": "🇲🇦 Fabriqué au Maroc",
    "footer.copy": "© 2026 Warda Beauté — wardabeaute.com | 🇲🇦 Casablanca, Maroc | Paiement 100% à la livraison",

  "cmp.velvastretch.vs": "vs les crèmes / huiles classiques en pharmacie",
  "cmp.silkstop.vs": "vs les crèmes dépilatoires chimiques",
  "cmp.collaglow.vs": "vs une crème au collagène",
  "cmp.kit-collagene.vs": "vs un seul produit ou le laser",
    "cmp.criterion": "Critère",
    "cmp.alt": "L'alternative",
    "ab.title": "Pourquoi nos clientes nous font confiance",
    "ab.sub": "Une marque marocaine, pensée pour la peau méditerranéenne.",
    "ab.safeTitle": "Formulé en toute sécurité",
    "ab.safeBody": "Formules testées sous contrôle dermatologique, sans parabènes ni sulfates. Pensées pour la peau méditerranéenne, même sensible. VelvaStretch™ est sans retinol — donc sûr pendant et après la grossesse.",
    "ab.halalTitle": "Halal & Vegan certifié",
    "ab.halalBody": "Collagène marin (poisson), base pectine végétale sans gélatine animale. Certifié halal & vegan — parce que pour vous, ce qui entre dans la peau compte autant que ce qui entre dans l'assiette.",
    "ab.guaranteeTitle": "Garantie 4 semaines",
    "ab.guaranteeBody": "Vous essayez, vous voyez. Si vous n'êtes pas convaincue après 4 semaines d'utilisation régulière, on rembourse — sans discussion, sans retour compliqué.",
    "ab.codTitle": "Paiement à la réception",
    "ab.codBody": "Vous ne payez rien à l'avance. Le colis arrive chez vous en 24–48h partout au Maroc, et vous réglez seulement à la livraison. Zéro risque, zéro avance.",
    "ab.trust": "Confiance d'abord",

    "collection.title": "Nos Produits",
    "collection.sub": "Trois soins pensés pour la peau marocaine.",
    "faqPage.title": "Questions fréquentes",
    "faqPage.sub": "Tout ce que tu veux savoir avant de commander.",
    "story.title": "Notre Histoire",
    "story.sub": "Comment une cuisine de Casablanca est devenue une marque.",
    "story.p1": "Warda Beauté est née d'un constat simple : les femmes marocaines méritent des produits efficaces, fabriqués ici, à des prix justes. Pas d'importation. Pas d'intermédiaire. Juste la science et les ingrédients que votre peau réclame.",
    "story.p2": "🇲🇦 Fabriqué au Maroc · 🔬 Testé dermatologiquement · 💳 Paiement à la livraison · 🚚 Livraison 24–48h",
    "story.secEyebrow": "Conviction",
    "story.secTitle": "La science au service de la femme marocaine",
    "story.sec1": "Trois produits. Trois réponses à trois problèmes réels : vergetures, repousse des poils, et perte de collagène.",
    "story.sec2": "Pas de catalogue infini. Pas de marketing vide. Juste de l'efficacité — livrée chez toi, payée à la réception.",
    "story.quote": "Warda Beauté n'est pas qu'une marque — c'est ta réponse.",
    "contact.title": "Nous contacter",
    "contact.sub": "WhatsApp, email ou réseaux — on répond vite.",
    "contact.whatsapp": "WhatsApp — réponse rapide",
    "contact.instagram": "Instagram: @wardabeaute.ma",
    "contact.tiktok": "TikTok: @wardabeaute.ma",
    "contact.email": "Email: contact@wardabeaute.com",
    "contact.address": "Casablanca, Maroc",
    "returnPage.title": "Livraison & Retours",
    "returnPage.sub": "Tout sur la livraison, le COD et les retours.",
    "privacy.title": "Politique de confidentialité",
    "notFound.title": "Page introuvable",
    "notFound.sub": "Cette page n'existe pas ou plus.",
    "notFound.cta": "Retour à l'accueil",
    "confirm.title": "Merci pour ta commande !",
    "home.heroEyebrow": "✦ Marque marocaine · 100% naturel · Paiement à la livraison ✦",
    "home.heroH1": "La beauté authentique, née au Maroc",
    "home.heroAr": "Ta beauté mérite le meilleur — conçue ici, pour ta peau à toi.",
    "home.discover": "Découvrir nos produits",
    "home.story": "Notre histoire",
    "home.heroFooter": "🚚 Livraison gratuite · 💳 Paiement à la livraison · ↩️ Retour 30 jours",
    "home.problemTitle": "Tu connais cette sensation, n'est-ce pas ?",
    "home.problemBody": "Celle de cacher ton ventre au hammam. De ranger les robes d'été. De détourner les yeux devant le miroir après la grossesse, ou de voir ta peau perdre sa fermeté à 30 ans. Tu as essayé les huiles, les crèmes, les séances de laser — et tu as attendu.",
    "home.problemMicro": "Tu as tout essayé, et le résultat ? Rien.",
    "home.storyEyebrow": "Notre Histoire",
    "home.storyTitle": "Née d'une conviction marocaine",
    "home.story1": "Warda Beauté est née dans une cuisine à Casablanca. Sa fondatrice cherchait une solution aux vergetures après sa grossesse et ne trouvait que des produits importés chers ou sans transparence.",
    "home.story2": "Elle a formulé ses propres solutions — avec des ingrédients sourcés au Maroc, testés sur sa peau, sur celle de ses amies, de sa sœur, de sa mère.",
    "home.storyQuote": "Notre but est un : chaque femme marocaine se sent belle sans cacher son corps.",
    "home.featuredEyebrow": "Nos Produits",
    "home.featuredTitle": "Trois solutions. Un seul objectif : te sentir belle.",
    "home.scienceEyebrow": "La science, pas le marketing",
    "home.scienceTitle": "Pourquoi nos actifs sont différents",
    "home.sci1t": "Centella Asiatica",
    "home.sci1d": "L'actif le plus documenté contre les vergetures : des études montrent qu'il stimule la synthèse du collagène de type I dans le derme.",
    "home.sci2t": "Collagène marin hydrolysé",
    "home.sci2d": "Découpé en petits peptides, il est absorbé par l'intestin puis transporté jusqu'à la peau — la forme la plus biodisponible (vs la crème, dont la molécule ne traverse pas la peau).",
    "home.sci3t": "Vitamine C (Acérola)",
    "home.sci3d": "Le cofacteur OBLIGATOIRE pour que ton corps fabrique du collagène. Sans elle, les peptides ne se transforment pas.",
    "home.bundleTitle": "Le Duo Collagène — Kit Collagène Inside & Outside",
    "home.bundleSub": "VelvaStretch™ + CollaGlow™ : l'extérieur et l'intérieur, réunis pour des résultats que tu vois.",
    "home.bundleCta": "Découvrir le Kit Collagène",
    "home.howTitle": "Comment commander? C'est simple.",
    "home.how1t": "Choisis ton produit",
    "home.how1d": "Sélectionne ton produit. Pas de compte, pas de carte.",
    "home.how2t": "Laisse tes coordonnées",
    "home.how2d": "Nom + téléphone. On t'appelle pour confirmer.",
    "home.how3t": "Reçois et paie",
    "home.how3d": "Tu reçois en 24–48h. Tu paies cash au livreur.",
    "home.socialSuffix": " femmes marocaines satisfaites",
    "home.whyTitle": "Pourquoi des milliers de Marocaines nous font confiance?",
    "home.why1t": "100% Ingrédients Naturels",
    "home.why1d": "Chaque formule est construite autour d'ingrédients que tu connais.",
    "home.why2t": "Fabriqué au Maroc",
    "home.why2d": "Formulé et fabriqué au Maroc. Aucun intermédiaire.",
    "home.why3t": "Testé Dermatologiquement",
    "home.why3d": "Formules testées sur peau sensible marocaine.",
    "home.why4t": "Paiement à la livraison",
    "home.why4d": "Tu ne paies qu'à la livraison. Aucun risque.",
    "home.why5t": "Livraison 24–48h",
    "home.why5d": "On livre partout au Maroc.",
    "home.why6t": "Garantie 4 semaines",
    "home.why6d": "Résultats pas visibles? On rembourse.",
    "home.finalTitle": "Tu mérites de commencer aujourd'hui",
    "home.finalBody": "Chaque jour que tu attends est un jour de plus à cacher ton corps. Warda Beauté est là, formulée pour toi, livrée chez toi, payée à la livraison.",
    "home.finalCta1": "Découvrir nos produits",
    "home.finalCta2": "Voir le Kit Collagène",
  },

  ar: {
    "addToCart": "أضيفي للسلة",
    "cart": "السلة",
    "quantity": "الكمية :",
    "qtyLabel": "الكمية",
    "total": "المجموع",
    "subtotal": "المجموع الفرعي",
    "free": "فابور",
    "freeShipping": "توصيل فابور",
    "save": "وفّري",
    "youSave": "كتوفّري",
    "new": "جديد",
    "bestseller": "الأكثر طلباً",
    "reviews": "تقييم",
    "outOfStock": "سالينا المخزون",
    "inStock": "متوفر فالمخزون",
    "from": "ابتداءً من",
    "trust": "ثقة وأمان",
    "guarantee": "ضمان 4 سيمانات",
    "delivery": "التوصيل",
    "paymentCOD": "الدفع عند الاستلام",
    "contactUs": "تواصلي معانا",
    "allProducts": "شوفي جميع المنتجات",
    "ourProducts": "المنتجات ديالنا",
    "ourStory": "قصتنا",
    "returns": "سياسة الإرجاع",
    "tracking": "تتبّع الطلب",
    "shippingCOD": "التوصيل والدفع عند الاستلام",
    "conditions": "شروط الاستخدام",
    "privacy": "سياسة الخصوصية",
    "menu": "القائمة",
    "close": "إغلاق",
    "cartAria": "سلة المشتريات",
    "continueShopping": "كمّلي التسوق ديالك",
    "remove": "حذفي",

    "nav.notreHistoire": "قصتنا",
    "nav.products": "المنتجات ديالنا",
    "nav.velvastretch": "VelvaStretch™",
    "nav.silkstop": "SilkStop™",
    "nav.collaglow": "CollaGlow™",
    "nav.kit": "Kit Collagène Inside & Outside",
    "nav.contact": "تواصلي معانا",
    "nav.whatsapp": "واتساب",
    "nav.email": "البريد الإلكتروني",
    "nav.instagram": "إنستغرام",
    "nav.tiktok": "تيك توك",
    "nav.retour": "سياسة الإرجاع",
    "nav.suivi": "تتبّع الطلب",
    "nav.livraison": "التوصيل",
    "nav.conditions": "شروط الاستخدام",

    "announcement": "🇲🇦 ماركة مغربية · 💳 الدفع عند الاستلام · 🚚 التوصيل 24–48 ساعة",
    "announce.1": "🚚 توصيل فابور فكل المغرب — والدفع عند الاستلام",
    "announce.2": "🌹 مصنوع فالمغرب | 100% طبيعي | نتائج مضمونة",
    "announce.3": "⭐ أكثر من 2400 مغربية راضية هاد الشهر",
    "tb.natural": "100% مكونات طبيعية",
    "tb.madein": "مصنوع فالمغرب",
    "tb.cod": "الدفع عند الاستلام",
    "tb.derma": "مجرّب من أطباء الجلد",
    "tb.ship": "التوصيل 24–48 ساعة",

    "pp.whyLove": "علاش غادي تبغيه",
    "pp.science": "التركيبة العلمية",
    "pp.ingredients": "المكونات الأساسية",
    "pp.howTo": "طريقة الاستعمال",
    "pp.steps": "فـ 5 خطوات ساهلة",
    "pp.forYouIf": "هاد المنتج مناسب ليك إيلا:",
    "pp.testimonials": "شهادات الزبونات ديالنا",
    "pp.moreResults": "باش تحصلي على نتائج أفضل",
    "pp.alsoBought": "الزبونات اللي خداو {name} خداو معاه حتى",
    "pp.faq": "الأسئلة الشائعة",
    "pp.viewInci": "شوفي لائحة المكونات كاملة (INCI)",
    "pp.comparisonTitle": "علاش تختارينا وماشي البدائل الأخرى؟",
    "pp.ceLabel": "الفوائد ديالو لبشرتك",

    "kit.problemTitle": "كتعرفي هاد الإحساس، ياك؟",
    "kit.problemBody": "إحساس أنك تخبي كرشك فالحمام، ولا ترجعي حوايج الصيف للدولاب، ولا تهربي من الشوفة فالمراية من بعد الولادة. علامات التمدد، والبشرة اللي فقدات النضارة والمرونة ديالها... جربتي الزيوت، الكريمات، وحصص الليزر وبقيتي كتسناي النتيجة.",
    "kit.problemMicro": "جربتي كلشي، والنتيجة؟ والو.",
    "kit.scienceEyebrow": "العلم ماشي مجرد إشهار",
    "kit.scienceTitle": "علاش هاد الحل كيعطي نتيجة حقيقية",
    "kit.sci1": "فـ 25 عام، الجسم كينقص إنتاج الكولاجين بـ 1% كل عام. وفـ 35 عام، البشرة كتفقد المرونة ديالها. الكريمات العادية كتبقى غير فالسطح وما كتقدرش تعاود تبني الكولاجين اللي كيتصنع من الداخل.",
    "kit.sci2": "على هادشي منتج واحد بوحدو ما كافيش، خاصك تعالجي المشكل من الجيهتين بجوج:",
    "kit.sci3": "الدراسات العلمية واضحة: ملي كتعالجي من الداخل ومن برا فنفس الوقت، كتحصلي على نتيجة مضاعفة. تحليل شامل لـ 26 دراسة سريرية (1721 امرأة) كأكد التحسن الكبير فالترطيب والمرونة.",
    "kit.synergy": "دراسة سريرية على نساء بين 45 و 54 عام: نقص حتى لـ -31% فالتجاعيد، +23% زيادة فالمرونة، و +25% تحسن فالنضارة فـ 12 سيمانة.",
    "kit.authorityTitle": "علاش تقدري تثقي فمنتجاتنا",
    "kit.benefitsTitle": "النتائج اللي غادي تشوفيها",
    "kit.socialTitle": "زبونات جربو هاد الثنائي وعجبهم",
    "kit.ritualEyebrow": "طريقة الاستعمال",
    "kit.ritualTitle": "الروتين فـ 2 خطوات ساهلين",
    "kit.ritualNote": "فـ 4 سيمانات غادي تشوفي الفرق، وفـ 12 سيمانة غادي ترجعي ثقتك فجسمك كاملة. 🌹",
    "kit.faqTitle": "الأسئلة الشائعة",
    "kit.riskTitle": "بلا حتى مخاطرة، ثقة مضمونة 100%",
    "kit.riskBody": "الدفع عند الاستلام — ما كتخلصي حتى كيوصلك الكولي ليدك. وإيلا ما عجباتكش النتيجة فـ 4 سيمانات، كنرجعو ليك فلوسك كاملة بلا نقاش.",
    "kit.finalTitle": "Kit Collagène Inside & Outside",
    "kit.finalSub": "علاج متكامل من الداخل ومن برا، بثمن منتج واحد تقريباً.",
    "kit.viewAll": "شوفي جميع المنتجات",
    "kit.save": "كتوفّري",
    "kit.badge1": "🇲🇦 مصنوع فالمغرب",
    "kit.badge2": "🧪 مجرّب عند أطباء الجلد",
    "kit.badge3": "🌿 حلال ونباتي 100% (Vegan)",
    "kit.badge4": "🚫 بلا بارابين وبلا سلفات",
    "kit.badge5": "🔬 مركّب فمختبرات الدار البيضاء",
    "kit.badge6": "↩️ ضمان 4 سيمانات",
    "kit.urgency": "⚡ عرض محدود — الكمية قريبة تسالي",
    "kit.extTitle": "🩹 من برا — VelvaStretch™",
    "kit.extBody": "سيروم بالكولاجين البحري المحلل كيخترق بعمق 1.5× أكثر من كولاجين البقر، باش يخفف علامات التمدد ويشد البشرة.",
    "kit.intTitle": "💊 من الداخل — CollaGlow™",
    "kit.intBody": "2500 مغ كولاجين بحري محلل + حمض الهيالورونيك + فيتامين C + بيوتين، باش يبني البشرة والشعر والظفار من الداخل.",
    "kit.insideEyebrow": "التركيبة",
    "kit.insideTitle": "شنو كاين داخل الباك",
    "kit.insideBody": "جوج منتجات كيكملو بعضهم لهدف واحد: يعيدو بناء بشرتك من الداخل ومن برا.",
    "kit.social1": "⭐ 4.9/5 من أكثر من 2600 تقييم",
    "kit.social2": "🇲🇦 أكثر من 12000 زبونة راضية",
    "kit.social3": "🚚 94% كيتوصلو فـ 48 ساعة",

    "as.title": "علاش الزبونات ديالنا كيثقو فينا",
    "as.sub": "ماركة مغربية، مصممة خصيصاً للبشرة المغربية.",
    "as.authorityTitle": "تركيبات آمنة ومضمونة",
    "as.authorityBody": "تركيبات مجربة ومختبرة من أطباء الجلد، بدون بارابين وبدون سلفات. مصممة للبشرة المغربية حتى الحساسة. سيروم VelvaStretch™ خالي من الريتينول — يعني آمن تماماً وقت الحمل والرضاعة.",
    "as.halalTitle": "معتمد حلال ونباتي 100%",
    "as.halalBody": "كولاجين بحري طبيعي، بقاعدة بكتين نباتية بدون جيلاتين حيواني. معتمد حلال ونباتي 100% — حيت اللي كيدخل للبشرة ديالك عندو نفس الأهمية ديال اللي كتاكليه.",
    "as.guaranteeTitle": "ضمان استرجاع لمدة 4 سيمانات",
    "as.guaranteeBody": "جربي وشوفي النتيجة. إيلا ما كنتيش راضية بعد 4 سيمانات ديال الاستعمال المنتظم، كنرجعو ليك فلوسك كاملة — بلا نقاش وبلا أي تعقيد.",
    "as.codTitle": "الدفع عند الاستلام",
    "as.codBody": "ما كتخلصي والو مسبقاً. الكولي كيوصلك حتى للدار فـ 24–48 ساعة فكل مدن المغرب، وكتخلصي للموزع ملي كتوصلك طلبيتك.",
    "as.codTrust": "الثقة والراحة أولاً",

    "cart.title": "سلة المشتريات",
    "cart.empty": "السلة ديالك خاوية",
    "cart.emptyCta": "اكتشفي المنتجات ديالنا",
    "cart.youMayLike": "💡 غادي يعجبك حتى هاد العرض :",
    "cart.subtotal": "المجموع الفرعي",
    "cart.checkout": "إتمام الطلب",
    "cart.freeShip": "توصيل فابور مشمول",

    "co.title": "إتمام الطلب",
    "co.name": "الاسم الكامل",
    "co.namePh": "مثال: سميرة بنعلي",
    "co.phone": "رقم الهاتف",
    "co.phonePh": "06/07 XXXXXXXX",
    "co.address": "عنوان التوصيل",
    "co.addressPh": "الحي، الزنقة، رقم الدار...",
    "co.city": "المدينة",
    "co.cityPh": "الدار البيضاء",
    "co.notes": "ملاحظات للتوصيل (اختياري)",
    "co.notesPh": "طابق، علامة قريبة...",
    "co.cod": "الدفع عند الاستلام (COD)",
    "co.codNote": "ما كتخلصي والو دابا. الموزع كياخد الخلاص ملي كيوصلك الكولي ليدك.",
    "co.submit": "أكدي الطلب دابا",
    "co.processing": "جاري تأكيد الطلب...",
    "co.summary": "ملخص الطلب",
    "co.success": "تم تسجيل طلبك بنجاح!",
    "co.successBody": "شكراً ليك! الفريق ديالنا غادي يتصل بيك دغيا لتأكيد العنوان. والدفع كيكون عند الاستلام.",
    "co.error": "وقع خطأ أثناء إرسال الطلب. عاودي حاولي مرة أخرى.",
    "co.close": "إغلاق",
    "co.nameReq": "الاسم الكامل ضروري",
    "co.phoneReq": "رقم هاتف غير صالح. مثال: 0612345678 أو 0712345678",
    "co.cityReq": "المدينة ضرورية",
    "co.secure": "🔒 معلوماتك محمية ومؤمنة 100% · ⚡ كاين إقبال كبير على هاد المنتج",
    "co.back": "رجوع",
    "co.errorMorocco": "سمحي لينا، الطلبات متوفرة فقط داخل المغرب 🇲🇦.",
    "co.errorPhone": "رقم هاتف غير صالح. مثال: 0612345678 أو 0712345678",
    "co.errorBlocked": "تعذر الوصول من هذه الشبكة.",
    "co.errorGeneric": "وقع خطأ غير متوقع. عاودي حاولي مرة أخرى.",
    "co.upsellBody": "العناية المتكاملة من الداخل ومن برا. وفّري 49 درهم ملي كتاخديهم بجوج.",
    "co.upsellBoth": "خديتي الباك كامل 🌹 — كنهديو ليك خصم −{discount} درهم على الكوموند ديالك.",
    "co.upsellSave": "كتوفّري {discount} درهم · العرض كيسالي فـ {sec} ثانية",
    "co.upsellAdd": "زيدي {name} بخصم −{discount} درهم",
    "co.upsellApply": "استافدي من خصم −{discount} درهم",
    "co.upsellNo": "لا، شكراً",

    "footer.badge": "🇲🇦 صنع فالمغرب بعناية",
    "footer.copy": "© 2026 Warda Beauté — wardabeaute.com | 🇲🇦 الدار البيضاء، المغرب | الدفع 100% عند الاستلام",

    "cmp.velvastretch.vs": "مقارنة مع الكريمات والزيوت العادية فالصيدليات",
    "cmp.silkstop.vs": "مقارنة مع كريمات إزالة الشعر الكيميائية",
    "cmp.collaglow.vs": "مقارنة مع كريمات الكولاجين العادية",
    "cmp.kit-collagene.vs": "مقارنة مع منتج واحد بوحدو أو جلسات الليزر المكلفة",
    "cmp.criterion": "المعيار",
    "cmp.alt": "البدائل الأخرى",
    "ab.title": "علاش الزبونات ديالنا كيثقو فينا",
    "ab.sub": "ماركة مغربية، مصممة خصيصاً للبشرة المغربية.",
    "ab.safeTitle": "تركيبات آمنة ومضمونة",
    "ab.safeBody": "تركيبات مجربة ومختبرة من أطباء الجلد، بدون بارابين وبدون سلفات. مصممة للبشرة المغربية حتى الحساسة. سيروم VelvaStretch™ خالي من الريتينول — يعني آمن تماماً وقت الحمل والرضاعة.",
    "ab.halalTitle": "معتمد حلال ونباتي 100%",
    "ab.halalBody": "كولاجين بحري طبيعي، بقاعدة بكتين نباتية بدون جيلاتين حيواني. معتمد حلال ونباتي 100% — حيت اللي كيدخل للبشرة ديالك عندو نفس الأهمية ديال اللي كتاكليه.",
    "ab.guaranteeTitle": "ضمان استرجاع لمدة 4 سيمانات",
    "ab.guaranteeBody": "جربي وشوفي النتيجة. إيلا ما كنتيش راضية بعد 4 سيمانات ديال الاستعمال المنتظم، كنرجعو ليك فلوسك كاملة — بلا نقاش وبلا أي تعقيد.",
    "ab.codTitle": "الدفع عند الاستلام",
    "ab.codBody": "ما كتخلصي والو مسبقاً. الكولي كيوصلك حتى للدار فـ 24–48 ساعة فكل مدن المغرب، وكتخلصي للموزع ملي كتوصلك طلبيتك.",
    "ab.trust": "الثقة والراحة أولاً",

    "collection.title": "المنتجات ديالنا",
    "collection.sub": "حلول طبيعية وفعالة مصممة للبشرة المغربية.",
    "faqPage.title": "الأسئلة الشائعة",
    "faqPage.sub": "كل ما تبغي تعرفيه قبل ما تديري الطلب ديالك.",
    "story.title": "قصتنا",
    "story.sub": "كيفاش بدات فكرة Warda Beauté من الدار البيضاء حتى ولات ماركة مغربية موثوقة.",
    "story.p1": "Warda Beauté بدات من فكرة بسيطة: المرأة المغربية كتستحق منتجات عناية فعالة، مصنوعة هنا فالمغرب، وبأثمنة مناسبة وعادلة. بلا استيراد، وبلا وسطاء. غير العلم الموثوق والمكونات الطبيعية اللي كتحتاجها بشرتك.",
    "story.p2": "🇲🇦 مصنوع فالمغرب · 🔬 مجرّب ديرماتولوجياً · 💳 الدفع عند الاستلام · 🚚 توصيل سريع فـ 24–48 ساعة",
    "story.secEyebrow": "القناعة ديالنا",
    "story.secTitle": "العلم فالخدمة ديال جمال المرأة المغربية",
    "story.sec1": "3 منتجات متخصصة لـ 3 مشاكل حقيقية: علامات التمدد، بطء نمو الشعر، وفقدان مرونة ونضارة الكولاجين.",
    "story.sec2": "بلا كثرة المنتجات بلا فائدة. بلا وعود خاوية. غير الفعالية والنتيجة المضمونة — توصلك لدارك، وتخلصي ملي تستلميها.",
    "story.quote": "Warda Beauté ماشي غير ماركة — هي الحل اللي كتستحقيه لجمالك وثقتك فراسك.",
    "contact.title": "تواصلي معانا",
    "contact.sub": "واتساب، إيميل أو مواقع التواصل — كنجاوبوك بسرعة وبكل سرور.",
    "contact.whatsapp": "واتساب — جواب سريع",
    "contact.instagram": "إنستغرام: @wardabeaute.ma",
    "contact.tiktok": "تيك توك: @wardabeaute.ma",
    "contact.email": "البريد الإلكتروني: contact@wardabeaute.com",
    "contact.address": "الدار البيضاء، المغرب",
    "returnPage.title": "التوصيل وسياسة الإرجاع",
    "returnPage.sub": "كل المعلومات على التوصيل، الدفع عند الاستلام، والإرجاع.",
    "privacy.title": "سياسة الخصوصية",
    "notFound.title": "الصفحة غير موجودة",
    "notFound.sub": "هاد الصفحة ما بقاتش كاينة أو الرابط غير صحيح.",
    "notFound.cta": "رجعي للصفحة الرئيسية",
    "confirm.title": "شكراً على الطلب ديالك !",
    "home.heroEyebrow": "✦ ماركة مغربية · 100% طبيعي · الدفع عند الاستلام ✦",
    "home.heroH1": "الجمال الأصيل، تولد هنا فالمغرب",
    "home.heroAr": "جمالك كيستحق الأفضل — منتجات مصممة هنا، خصيصاً لبشرتك.",
    "home.discover": "اكتشفي المنتجات ديالنا",
    "home.story": "قصتنا",
    "home.heroFooter": "🚚 توصيل فابور · 💳 الدفع عند الاستلام · ↩️ ضمان استرجاع 30 يوم",
    "home.problemTitle": "كلنا كنعرفو هاد الإحساس، ياك؟",
    "home.problemBody": "إحساس أنك تخبي كرشك فالحمام، ولا ترجعي حوايج الصيف للدولاب، ولا تهربي من الشوفة فالمراية من بعد الولادة ولا ملي كتبدا البشرة تفقد النضارة ديالها مع الوقت. جربتي الزيوت، جربتي الكريمات، وجلسات الليزر وبقيتي كتسناي النتيجة.",
    "home.problemMicro": "جربتي كلشي، والنتيجة؟ والو.",
    "home.storyEyebrow": "قصتنا",
    "home.storyTitle": "بدات من قناعة مغربية حقيقية",
    "home.story1": "Warda Beauté تولدات فقلب الدار البيضاء. المؤسِسة ديالها كانت كتقلب على حل فعال لعلامات التمدد من بعد الولادة، وما كانتش كتلقى غير منتجات مستوردة غالية وبلا شفافية فالمكونات.",
    "home.story2": "صممت حلولها بنفسها — بمكونات مغربية طبيعية، مجربة على بشرتها، وبشرة صحاباتها، وعائلتها، حتى تأكدات من النتيجة.",
    "home.storyQuote": "الهدف ديالنا واحد: كل امرأة مغربية تحس بجمالها وثقتها فراسها بلا ما تخبي جسمها.",
    "home.featuredEyebrow": "المنتجات ديالنا",
    "home.featuredTitle": "3 حلول فعالة لهدف واحد: ترجعي ثقتك وجمالك الطبيعي.",
    "home.scienceEyebrow": "العلم ماشي مجرد إشهار",
    "home.scienceTitle": "علاش المكونات الفعالة ديالنا متميزة",
    "home.sci1t": "Centella Asiatica",
    "home.sci1d": "أكثر مكون مدروس علمياً ضد علامات التمدد: كيحفز إنتاج الكولاجين من النوع الأول فالطبقات العميقة للبشرة.",
    "home.sci2t": "كولاجين بحري محلل",
    "home.sci2d": "مقسم لبيبتيدات صغيرة كيمتصها الجسم بسهولة وسرعة باش توصل للبشرة — أفضل وأسرع امتصاصاً مقارنة بالكريمات السطحية.",
    "home.sci3t": "فيتامين C الطبيعي (Acérola)",
    "home.sci3d": "العنصر الأساسي والضروري باش الجسم يقدر يصنع الكولاجين. بدونو، البيبتيدات ما كيتحولوش لكولاجين فعال.",
    "home.bundleTitle": "ثنائي الكولاجين — Kit Collagène Inside & Outside",
    "home.bundleSub": "VelvaStretch™ + CollaGlow™ : من برا ومن الداخل، مجموعين باش يعطيوك أفضل وأسرع نتيجة.",
    "home.bundleCta": "اكتشفي Kit Collagène",
    "home.howTitle": "كيفاش تديري الطلب؟ ساهل وبسيط.",
    "home.how1t": "اختاري المنتج ديالك",
    "home.how1d": "اختاري العرض المناسب ليك، بلا ما تحتاجي حساب ولا بطاقة بنكية.",
    "home.how2t": "عمّري معلوماتك",
    "home.how2d": "غير الاسم ورقم الهاتف، وحنا كنتصلو بيك باش نأكدو الطلب.",
    "home.how3t": "استلمي وخلصي",
    "home.how3d": "الطلبية كتوصلك حتى لباب دارك فـ 24–48 ساعة، وكتخلصي كاش للموزع.",
    "home.socialSuffix": " امرأة مغربية راضية على النتائج",
    "home.whyTitle": "علاش الآلاف ديال المغربيات كيثقو فـ Warda Beauté؟",
    "home.why1t": "100% مكونات طبيعية",
    "home.why1d": "كل تركيبة مصممة بمكونات طبيعية نقية ومختارة بعناية.",
    "home.why2t": "مصنوع فالمغرب",
    "home.why2d": "تركيب وتصنيع محلي 100% بمعايير جودة عالية وبلا وسطاء.",
    "home.why3t": "مجرّب من أطباء الجلد",
    "home.why3d": "تركيبات آمنة ومختبرة ومناسبة حتى للبشرة الحساسة.",
    "home.why4t": "الدفع عند الاستلام",
    "home.why4d": "ما كتخلصي حتى كتوصلك السلعة ليدك. بلا حتى مخاطرة.",
    "home.why5t": "توصيل فـ 24–48 ساعة",
    "home.why5d": "كنوصلو لجميع المدن والمناطق فالمغرب.",
    "home.why6t": "ضمان استرجاع لمدة 4 سيمانات",
    "home.why6d": "ما شفتيش نتيجة؟ كنرجعو ليك فلوسك كاملة.",
    "home.finalTitle": "أنتِ كتستحقي الأفضل — بداي اليوم",
    "home.finalBody": "كل نهار كتأجلي فيه، نهار زايد كتفردي فيه راسك وتخبي جمالك. Warda Beauté هنا باش تعاونك، بمنتجات فعالة كتوصلك حتى لدارك والدفع كيكون عند الاستلام.",
    "home.finalCta1": "اكتشفي المنتجات ديالنا",
    "home.finalCta2": "شوفي Kit Collagène",
  },
};

export type UIKey = keyof typeof ui.fr;

export function t(lang: Lang, key: string): string {
  return (lang === "ar" ? ui.ar : ui.fr)[key] ?? ui.fr[key] ?? key;
}
