import type { Lang } from "@/lib/lang";

type Dict = Record<string, string>;

export const ui: { fr: Dict; ar: Dict } = {
  fr: {
    "addToCart": "Ajouter au panier",
    "cart": "Panier",
    "quantity": "Quantité :",
    "qtyLabel": "Quantité",
    "total": "Total",
    "subtotal": "Sous-total",
    "free": "Gratuit",
    "freeShipping": "Livraison gratuite",
    "save": "Économisez",
    "youSave": "Vous économisez",
    "new": "Nouveau",
    "bestseller": "Bestseller",
    "reviews": "avis",
    "outOfStock": "Rupture",
    "inStock": "En stock",
    "from": "Dès",
    "trust": "Confiance",
    "guarantee": "Garantie 4 semaines",
    "delivery": "Livraison",
    "paymentCOD": "Paiement à la livraison",
    "contactUs": "Nous contacter",
    "allProducts": "Voir tous les produits",
    "ourProducts": "Nos Produits",
    "ourStory": "Notre Histoire",
    "returns": "Politique de retour",
    "tracking": "Suivi commande",
    "shippingCOD": "Livraison & COD",
    "conditions": "Conditions d'utilisation",
    "privacy": "Politique de confidentialité",
    "menu": "Menu",
    "close": "Fermer",
    "cartAria": "Panier",
    "continueShopping": "Continuer mes achats",
    "remove": "Retirer",

    "nav.notreHistoire": "Notre Histoire",
    "nav.products": "Nos Produits",
    "nav.velvastretch": "VelvaStretch™",
    "nav.silkstop": "SilkStop™",
    "nav.collaglow": "CollaGlow™",
    "nav.kit": "Kit Collagène Inside & Outside",
    "nav.contact": "Nous contacter",
    "nav.whatsapp": "WhatsApp",
    "nav.email": "Email",
    "nav.instagram": "Instagram",
    "nav.tiktok": "TikTok",
    "nav.retour": "Politique de retour",
    "nav.suivi": "Suivi commande",
    "nav.livraison": "Livraison",
    "nav.conditions": "Conditions d'utilisation",

    "announcement": "🇲🇦 Marque marocaine · 💳 Paiement à la livraison · 🚚 Livraison 24–48h",
    "announce.1": "🚚 Livraison gratuite partout au Maroc — Paiement à la livraison",
    "announce.2": "🌹 Fabriqué au Maroc | 100% naturel | résultats garantis",
    "announce.3": "⭐ +2 400 femmes marocaines satisfaites ce mois-ci",
    "tb.natural": "100% Ingrédients Naturels",
    "tb.madein": "Fabriqué au Maroc",
    "tb.cod": "Paiement à la livraison",
    "tb.derma": "Testé Dermatologiquement",
    "tb.ship": "Livraison 24–48h",

    "pp.whyLove": "Pourquoi tu vas l'aimer",
    "pp.science": "La science",
    "pp.ingredients": "Les ingrédients",
    "pp.howTo": "Comment utiliser",
    "pp.steps": "En 5 étapes",
    "pp.forYouIf": "Pour toi si :",
    "pp.testimonials": "Elles témoignent",
    "pp.moreResults": "Encore plus de résultats",
    "pp.alsoBought": "Les femmes qui ont pris {name} ont aussi pris",
    "pp.faq": "Questions fréquentes",
    "pp.viewInci": "Voir la liste INCI complète",
    "pp.comparisonTitle": "Pourquoi nous, et pas l'autre option ?",
    "pp.ceLabel": "Ce que ça fait",

    "kit.problemTitle": "Tu connais cette sensation, n'est-ce pas ?",
    "kit.problemBody": "Celle de cacher ton ventre au hammam. De ranger les robes courtes d'été. De détourner les yeux devant le miroir après la grossesse. Les vergetures, la peau qui a perdu sa fermeté… tu as essayé les huiles, les crèmes, les séances de laser. Et tu as attendu.",
    "kit.problemMicro": "Tu as tout essayé, et le résultat ? Rien.",
    "kit.scienceEyebrow": "La science, pas le marketing",
    "kit.scienceTitle": "Pourquoi ça marche enfin",
    "kit.sci1": "À 25 ans, ton corps produit 1% de collagène en moins chaque année. À 35, la fermeté fuit. Les crèmes classiques restent en surface — elles ne peuvent pas reconstruire ce qui se fabrique à l'intérieur.",
    "kit.sci2": "C'est pour ça qu'un seul produit ne suffit pas. Il faut attaquer sur les deux fronts :",
    "kit.sci3": "La recherche est claire : agir de l'intérieur et de l'extérieur en même temps donne plus que la somme des deux. Une méta-analyse de 26 études contrôlées (1 721 femmes) confirme l'amélioration nette de l'hydratation et de l'élasticité.",
    "kit.synergy": "Étude double-aveugle, femmes 45–54 ans : jusqu'à −31% de rides, +23% d'élasticité, +25% de fermeté en 12 semaines (vs placebo).",
    "kit.authorityTitle": "Pourquoi tu peux nous faire confiance",
    "kit.benefitsTitle": "Ce que tu vas voir",
    "kit.socialTitle": "Elles ont dit oui au duo",
    "kit.ritualEyebrow": "Comment l'utiliser",
    "kit.ritualTitle": "Le rituel en 2 gestes",
    "kit.ritualNote": "En 4 semaines, tu vois. En 12 semaines, tu ne te caches plus. 🌹",
    "kit.faqTitle": "Questions fréquentes",
    "kit.riskTitle": "Zéro risque. Vraie confiance.",
    "kit.riskBody": "Paiement à la livraison — tu ne payes que quand le colis arrive. Et si tu n'es pas convaincue en 4 semaines, on rembourse, sans discussion.",
    "kit.finalTitle": "Le Kit Collagène Inside & Outside",
    "kit.finalSub": "Les deux fronts, pour le prix d'un seul produit presque.",
    "kit.viewAll": "Voir tous les produits",
    "kit.save": "Vous économisez",
    "kit.badge1": "🇲🇦 Fabriqué au Maroc",
    "kit.badge2": "🧪 Testé dermatologiquement",
    "kit.badge3": "🌿 Halal & Vegan",
    "kit.badge4": "🚫 Sans paraben / sulfate",
    "kit.badge5": "🔬 Formulé au labo de Casablanca",
    "kit.badge6": "↩️ Garantie 4 semaines",
    "kit.urgency": "⚡ Offre limitée — stocks réduits",
    "kit.extTitle": "🩹 L'EXTÉRIEUR — VelvaStretch™",
    "kit.extBody": "Sérum au collagène marin hydrolysé qui pénètre 1,5× plus profondément que le collagène bovin, pour estomper les vergetures et redensifier la peau.",
    "kit.intTitle": "💊 L'INTÉRIEUR — CollaGlow™",
    "kit.intBody": "2 500 mg de collagène marin hydrolysé + acide hyaluronique + vitamine C + biotine, qui rebuild la peau, les cheveux et les ongles depuis la source.",
    "kit.insideEyebrow": "La formule",
    "kit.insideTitle": "Ce qu'il y a dans le kit",
    "kit.insideBody": "Deux produits complémentaires, une seule mission : reconstruire ta peau des deux côtés.",
    "kit.social1": "⭐ 4.9/5 sur 2 662 avis",
    "kit.social2": "🇲🇦 +12 000 clientes",
    "kit.social3": "🚚 94% livré en 48h",

    "as.title": "Pourquoi nos clientes nous font confiance",
    "as.sub": "Une marque marocaine, pensée pour la peau méditerranéenne.",
    "as.authorityTitle": "Formulé en toute sécurité",
    "as.authorityBody": "Formules testées sous contrôle dermatologique, sans parabènes ni sulfates. Pensées pour la peau méditerranéenne, même sensible. VelvaStretch™ est sans retinol — donc sûr pendant et après la grossesse.",
    "as.halalTitle": "Halal & Vegan certifié",
    "as.halalBody": "Collagène marin (poisson), base pectine végétale sans gélatine animale. Certifié halal & vegan — parce que pour vous, ce qui entre dans la peau compte autant que ce qui entre dans l'assiette.",
    "as.guaranteeTitle": "Garantie 4 semaines",
    "as.guaranteeBody": "Vous essayez, vous voyez. Si vous n'êtes pas convaincue après 4 semaines d'utilisation régulière, on rembourse — sans discussion, sans retour compliqué.",
    "as.codTitle": "Paiement à la livraison",
    "as.codBody": "Vous ne payez rien à l'avance. Le colis arrive chez vous en 24–48h partout au Maroc, et vous réglez seulement à la livraison. Zéro risque, zéro avance.",
    "as.codTrust": "Confiance d'abord",

    "cart.title": "Panier",
    "cart.empty": "Votre panier est vide",
    "cart.emptyCta": "Découvrir nos produits",
    "cart.youMayLike": "💡 Vous aimerez aussi (même prix d'origine) :",
    "cart.subtotal": "Sous-total",
    "cart.checkout": "Commander",
    "cart.freeShip": "Livraison gratuite incluse",

    "co.title": "Finaliser la commande",
    "co.name": "Nom complet",
    "co.namePh": "Ex : Samira Benali",
    "co.phone": "Téléphone",
    "co.phonePh": "0X XX XX XX XX",
    "co.address": "Adresse de livraison",
    "co.addressPh": "Rue, quartier, numéro…",
    "co.city": "Ville",
    "co.cityPh": "Casablanca",
    "co.notes": "Notes (optionnel)",
    "co.notesPh": "Point de repère, étage…",
    "co.cod": "Paiement à la livraison",
    "co.codNote": "Vous ne payez rien maintenant. Le livreur encaisse à la livraison.",
    "co.submit": "Confirmer la commande",
    "co.processing": "Traitement…",
    "co.summary": "Récapitulatif",
    "co.success": "Commande confirmée !",
    "co.successBody": "Merci ! Notre équipe vous appelle sous peu pour confirmer. Paiement à la livraison.",
    "co.error": "Une erreur est survenue. Réessayez.",
    "co.close": "Fermer",
    "co.nameReq": "Nom requis",
    "co.phoneReq": "Numéro marocain invalide. Ex: 0612345678",
    "co.cityReq": "Ville requise",
    "co.secure": "🔒 Vos données sont protégées · ⚡ 47 personnes regardent",
    "co.back": "Retour",
    "co.errorMorocco": "Désolé, les commandes sont réservées au Maroc 🇲🇦.",
    "co.errorPhone": "Numéro marocain invalide. Ex: 0612345678",
    "co.errorBlocked": "Accès non autorisé depuis ce réseau.",
    "co.errorGeneric": "Une erreur est survenue. Réessayez.",
    "co.upsellBody": "La beauté par l'intérieur + l'extérieur. Ensemble, ils valent 49 MAD de moins.",
    "co.upsellBoth": "Vous avez déjà le duo complet 🌹 — on vous offre −{discount} MAD sur votre commande.",
    "co.upsellSave": "Vous économisez {discount} MAD · expire dans {sec}s",
    "co.upsellAdd": "Ajouter {name} · −{discount} MAD",
    "co.upsellApply": "Appliquer −{discount} MAD",
    "co.upsellNo": "Non merci",

    "footer.badge": "🇲🇦 Fabriqué au Maroc",
    "footer.copy": "© 2026 Warda Beauté — wardabeaute.com | 🇲🇦 Casablanca, Maroc | Paiement 100% à la livraison",

  "cmp.velvastretch.vs": "vs les crèmes / huiles classiques en pharmacie",
  "cmp.silkstop.vs": "vs les crèmes dépilatoires chimiques",
  "cmp.collaglow.vs": "vs une crème au collagène",
  "cmp.kit-collagene.vs": "vs un seul produit ou le laser",
    "cmp.criterion": "Critère",
    "cmp.alt": "L'alternative",
    "ab.title": "Pourquoi nos clientes nous font confiance",
    "ab.sub": "Une marque marocaine, pensée pour la peau méditerranéenne.",
    "ab.safeTitle": "Formulé en toute sécurité",
    "ab.safeBody": "Formules testées sous contrôle dermatologique, sans parabènes ni sulfates. Pensées pour la peau méditerranéenne, même sensible. VelvaStretch™ est sans retinol — donc sûr pendant et après la grossesse.",
    "ab.halalTitle": "Halal & Vegan certifié",
    "ab.halalBody": "Collagène marin (poisson), base pectine végétale sans gélatine animale. Certifié halal & vegan — parce que pour vous, ce qui entre dans la peau compte autant que ce qui entre dans l'assiette.",
    "ab.guaranteeTitle": "Garantie 4 semaines",
    "ab.guaranteeBody": "Vous essayez, vous voyez. Si vous n'êtes pas convaincue après 4 semaines d'utilisation régulière, on rembourse — sans discussion, sans retour compliqué.",
    "ab.codTitle": "Paiement à la réception",
    "ab.codBody": "Vous ne payez rien à l'avance. Le colis arrive chez vous en 24–48h partout au Maroc, et vous réglez seulement à la livraison. Zéro risque, zéro avance.",
    "ab.trust": "Confiance d'abord",

    "collection.title": "Nos Produits",
    "collection.sub": "Trois soins pensés pour la peau marocaine.",
    "faqPage.title": "Questions fréquentes",
    "faqPage.sub": "Tout ce que tu veux savoir avant de commander.",
    "story.title": "Notre Histoire",
    "story.sub": "Comment une cuisine de Casablanca est devenue une marque.",
    "story.p1": "Warda Beauté est née d'un constat simple : les femmes marocaines méritent des produits efficaces, fabriqués ici, à des prix justes. Pas d'importation. Pas d'intermédiaire. Juste la science et les ingrédients que votre peau réclame.",
    "story.p2": "🇲🇦 Fabriqué au Maroc · 🔬 Testé dermatologiquement · 💳 Paiement à la livraison · 🚚 Livraison 24–48h",
    "story.secEyebrow": "Conviction",
    "story.secTitle": "La science au service de la femme marocaine",
    "story.sec1": "Trois produits. Trois réponses à trois problèmes réels : vergetures, repousse des poils, et perte de collagène.",
    "story.sec2": "Pas de catalogue infini. Pas de marketing vide. Juste de l'efficacité — livrée chez toi, payée à la réception.",
    "story.quote": "Warda Beauté n'est pas qu'une marque — c'est ta réponse.",
    "contact.title": "Nous contacter",
    "contact.sub": "WhatsApp, email ou réseaux — on répond vite.",
    "contact.whatsapp": "WhatsApp — réponse rapide",
    "contact.instagram": "Instagram: @wardabeaute",
    "contact.tiktok": "TikTok: @wardabeaute",
    "contact.email": "Email: hello@wardabeaute.com",
    "contact.address": "Casablanca, Maroc",
    "returnPage.title": "Livraison & Retours",
    "returnPage.sub": "Tout sur la livraison, le COD et les retours.",
    "privacy.title": "Politique de confidentialité",
    "notFound.title": "Page introuvable",
    "notFound.sub": "Cette page n'existe pas ou plus.",
    "notFound.cta": "Retour à l'accueil",
    "confirm.title": "Merci pour ta commande !",
    "home.heroEyebrow": "✦ Marque marocaine · 100% naturel · Paiement à la livraison ✦",
    "home.heroH1": "La beauté authentique, née au Maroc",
    "home.heroAr": "Ta beauté mérite le meilleur — conçue ici, pour ta peau à toi.",
    "home.discover": "Découvrir nos produits",
    "home.story": "Notre histoire",
    "home.heroFooter": "🚚 Livraison gratuite · 💳 Paiement à la livraison · ↩️ Retour 30 jours",
    "home.problemTitle": "Tu connais cette sensation, n'est-ce pas ?",
    "home.problemBody": "Celle de cacher ton ventre au hammam. De ranger les robes d'été. De détourner les yeux devant le miroir après la grossesse, ou de voir ta peau perdre sa fermeté à 30 ans. Tu as essayé les huiles, les crèmes, les séances de laser — et tu as attendu.",
    "home.problemMicro": "Tu as tout essayé, et le résultat ? Rien.",
    "home.storyEyebrow": "Notre Histoire",
    "home.storyTitle": "Née d'une conviction marocaine",
    "home.story1": "Warda Beauté est née dans une cuisine à Casablanca. Sa fondatrice cherchait une solution aux vergetures après sa grossesse et ne trouvait que des produits importés chers ou sans transparence.",
    "home.story2": "Elle a formulé ses propres solutions — avec des ingrédients sourcés au Maroc, testés sur sa peau, sur celle de ses amies, de sa sœur, de sa mère.",
    "home.storyQuote": "Notre but est un : chaque femme marocaine se sent belle sans cacher son corps.",
    "home.featuredEyebrow": "Nos Produits",
    "home.featuredTitle": "Trois solutions. Un seul objectif : te sentir belle.",
    "home.scienceEyebrow": "La science, pas le marketing",
    "home.scienceTitle": "Pourquoi nos actifs sont différents",
    "home.sci1t": "Centella Asiatica",
    "home.sci1d": "L'actif le plus documenté contre les vergetures : des études montrent qu'il stimule la synthèse du collagène de type I dans le derme.",
    "home.sci2t": "Collagène marin hydrolysé",
    "home.sci2d": "Découpé en petits peptides, il est absorbé par l'intestin puis transporté jusqu'à la peau — la forme la plus biodisponible (vs la crème, dont la molécule ne traverse pas la peau).",
    "home.sci3t": "Vitamine C (Acérola)",
    "home.sci3d": "Le cofacteur OBLIGATOIRE pour que ton corps fabrique du collagène. Sans elle, les peptides ne se transforment pas.",
    "home.bundleTitle": "Le Duo Collagène — Kit Collagène Inside & Outside",
    "home.bundleSub": "VelvaStretch™ + CollaGlow™ : l'extérieur et l'intérieur, réunis pour des résultats que tu vois.",
    "home.bundleCta": "Découvrir le Kit Collagène",
    "home.howTitle": "Comment commander? C'est simple.",
    "home.how1t": "Choisis ton produit",
    "home.how1d": "Sélectionne ton produit. Pas de compte, pas de carte.",
    "home.how2t": "Laisse tes coordonnées",
    "home.how2d": "Nom + téléphone. On t'appelle pour confirmer.",
    "home.how3t": "Reçois et paie",
    "home.how3d": "Tu reçois en 24–48h. Tu paies cash au livreur.",
    "home.socialSuffix": " femmes marocaines satisfaites",
    "home.whyTitle": "Pourquoi des milliers de Marocaines nous font confiance?",
    "home.why1t": "100% Ingrédients Naturels",
    "home.why1d": "Chaque formule est construite autour d'ingrédients que tu connais.",
    "home.why2t": "Fabriqué au Maroc",
    "home.why2d": "Formulé et fabriqué au Maroc. Aucun intermédiaire.",
    "home.why3t": "Testé Dermatologiquement",
    "home.why3d": "Formules testées sur peau sensible marocaine.",
    "home.why4t": "Paiement à la livraison",
    "home.why4d": "Tu ne paies qu'à la livraison. Aucun risque.",
    "home.why5t": "Livraison 24–48h",
    "home.why5d": "On livre partout au Maroc.",
    "home.why6t": "Garantie 4 semaines",
    "home.why6d": "Résultats pas visibles? On rembourse.",
    "home.finalTitle": "Tu mérites de commencer aujourd'hui",
    "home.finalBody": "Chaque jour que tu attends est un jour de plus à cacher ton corps. Warda Beauté est là, formulée pour toi, livrée chez toi, payée à la livraison.",
    "home.finalCta1": "Découvrir nos produits",
    "home.finalCta2": "Voir le Kit Collagène",
  },

  ar: {
    "addToCart": "أضيفي للسلة",
    "cart": "السلة",
    "quantity": "الكمية :",
    "qtyLabel": "الكمية",
    "total": "المجموع",
    "subtotal": "المجموع",
    "free": "مجاني",
    "freeShipping": "التوصيل بالخاوة",
    "save": "وفّري",
    "youSave": "كترشدي",
    "new": "جديد",
    "bestseller": "الأكثر مبيعاً",
    "reviews": "رأي",
    "outOfStock": "نفذ من المخزون",
    "inStock": "متوفر",
    "from": "من",
    "trust": "الثقة",
    "guarantee": "ضمان 4 سيمان",
    "delivery": "التوصيل",
    "paymentCOD": "الخلاص عند الاستلام",
    "contactUs": "تواصلي معانا",
    "allProducts": "شوفي جميع المنتجات",
    "ourProducts": "منتجاتنا",
    "ourStory": "قصتنا",
    "returns": "سياسة الرجوع",
    "tracking": "تتبّع الطلب",
    "shippingCOD": "التوصيل والخلاص عند الاستلام",
    "conditions": "شروط الاستخدام",
    "privacy": "سياسة الخصوصية",
    "menu": "القائمة",
    "close": "سدّي",
    "cartAria": "السلة",
    "continueShopping": "كملّي الشراء ديالك",
    "remove": "حيدي",

    "nav.notreHistoire": "قصتنا",
    "nav.products": "منتجاتنا",
    "nav.velvastretch": "VelvaStretch™",
    "nav.silkstop": "SilkStop™",
    "nav.collaglow": "CollaGlow™",
    "nav.kit": "Kit Collagène Inside & Outside",
    "nav.contact": "تواصلي معانا",
    "nav.whatsapp": "واتساب",
    "nav.email": "الإيمايل",
    "nav.instagram": "إنستغرام",
    "nav.tiktok": "تيك توك",
    "nav.retour": "سياسة الرجوع",
    "nav.suivi": "تتبّع الطلب",
    "nav.livraison": "التوصيل",
    "nav.conditions": "شروط الاستخدام",

    "announcement": "🇲🇦 ماركة مغربية · 💳 الخلاص عند الاستلام · 🚚 التوصيل 24–48 ساعة",
    "announce.1": "🚚 التوصيل بالخاوة فكل المغرب — الخلاص عند الاستلام",
    "announce.2": "🌹 مصنوع فالمغرب | 100% طبيعي | النتائج مضمونة",
    "announce.3": "⭐ كثر من 2400 مرا مغربية راضية هاد الشهر",
    "tb.natural": "100% مكونات طبيعية",
    "tb.madein": "مصنوع فالمغرب",
    "tb.cod": "الخلاص عند الاستلام",
    "tb.derma": "مجرّب من طرف دكاترة الجلد",
    "tb.ship": "التوصيل 24–48 ساعة",

    "pp.whyLove": "علاش غتبغيه",
    "pp.science": "العلم",
    "pp.ingredients": "المكونات",
    "pp.howTo": "كيفاش تستعمليه",
    "pp.steps": "فـ 5 ديور",
    "pp.forYouIf": "هادشي ليك إلا:",
    "pp.testimonials": "هوما قالو",
    "pp.moreResults": "باش تجيبي نتيجة كثر",
    "pp.alsoBought": "اللي شرات {name} شراتات حتى",
    "pp.faq": "أسئلة كثيرة",
    "pp.viewInci": "شوفي لائحة INCI كاملة",
    "pp.comparisonTitle": "علاش حنا، وماشي المور الآخر؟",
    "pp.ceLabel": "علاش هادشي لبشرتك",

    "kit.problemTitle": "كتعرف هاد الإحساس، أوراه؟",
    "kit.problemBody": "إحساس داكشي اللي كتخبي بيه كرشك فالحمام. اللي كترد بيه جلابيب الصيف القصار. اللي كتحاشى بيه المرايا من بعد الحمل. علامات التمدد، والبشرة اللي ضاعت رقايقتها… جربتي الزيوت، والكريمات، وجلسات الليزر. وكنتي كتستناي.",
    "kit.problemMicro": "كلشي جربتي، والنتيجة؟ لا والو.",
    "kit.scienceEyebrow": "العلم، ماشي التسويق",
    "kit.scienceTitle": "علاش خدام هاد المرة",
    "kit.sci1": "فـ 25 عام، الجسم ديالك كينقص فيه 1% ديال الكولاجين كل عام. فـ 35، المرونة كتّمشي. الكريمات العادية كيبقاو فالسطح — مابغيعاودوش يبنيو اللي كيتصنع من الداخل.",
    "kit.sci2": "على هادشي منتوج وحدو مابكفيش. خاصك تضربي من الجوج دوال:",
    "kit.sci3": "البحث واضح: كتشدّي من الداخل ومن لبراني فنفس الوقت، كتجي نتيجة كبر من مجموع الجوج وحدهم. ميتا-أناليس ديال 26 دراسة (1721 مرا) كتأكد التحسن الكبير فالترطيب والمرونة.",
    "kit.synergy": "دراسة مزدوجة التعمية، النساء فـ 45–54 عام: حتى -31% ديال التجاعيد، +23% ديال المرونة، +25% ديال المرونة فـ 12 سيمان (مقارنة بالبلاصيبو).",
    "kit.authorityTitle": "علاش تقدري ثقتي فينا",
    "kit.benefitsTitle": "اللي غتشوفي",
    "kit.socialTitle": "هوما قبلو بالدو",
    "kit.ritualEyebrow": "كيفاش تستعمليه",
    "kit.ritualTitle": "الروتين فزوز حركات",
    "kit.ritualNote": "فـ 4 سيمان كتشوفي. فـ 12 سيمان مابقيتي تخبي راسك. 🌹",
    "kit.faqTitle": "أسئلة كثيرة",
    "kit.riskTitle": "بلا خطر. ثقة حقيقية.",
    "kit.riskBody": "الخلاص عند الاستلام — ماتخلصيش غير ملي توصلك الشحنة. وعلاش ماقنعتيش فـ 4 سيمان، كنرجعو ليك الفلوس بلا نقاش.",
    "kit.finalTitle": "Kit Collagène Inside & Outside",
    "kit.finalSub": "الجوج وجوه، بثمن قريب لمنتوج واحد.",
    "kit.viewAll": "شوفي جميع المنتجات",
    "kit.save": "كترشدي",
    "kit.badge1": "🇲🇦 مصنوع فالمغرب",
    "kit.badge2": "🧪 مجرّب ديرماتولوجياً",
    "kit.badge3": "🌿 حلال وفيجان",
    "kit.badge4": "🚫 بلا بارابان ولا سولفات",
    "kit.badge5": "🔬 مركّب فلابو ديال الدار البيضاء",
    "kit.badge6": "↩️ ضمان 4 سيمان",
    "kit.urgency": "⚡ عرض محدود — المخزون قلّ",
    "kit.extTitle": "🩹 لبراني — VelvaStretch™",
    "kit.extBody": "السيروم بالكولاجين البحري المحلل كيدخل لعمق 1.5× أكثر من الكولاجين ديال البقر، باش يخفّف علامات التمدد ويشدّ الجلد.",
    "kit.intTitle": "💊 الداخل — CollaGlow™",
    "kit.intBody": "2500 ميليغرام ديال الكولاجين البحري المحلل + الـ Acide Hyaluronique + الفيتامين C + الـ Biotine، اللي كيعاون يبني البشرة والشعر والضوافر من الداخل.",
    "kit.insideEyebrow": "التركيبة",
    "kit.insideTitle": "شنو كاين فالكيت",
    "kit.insideBody": "زوج منتوجات مكمّلين، وهدف واحد: يعاونو يبنيو بشرتك من الجوج دوال.",
    "kit.social1": "⭐ 4.9/5 على 2662 رأي",
    "kit.social2": "🇲🇦 كثر من 12 000 زبونة",
    "kit.social3": "🚚 94% توصّل فـ 48 ساعة",

    "as.title": "علاش الزبونات ديالنا كيثقو فينا",
    "as.sub": "ماركة مغربية، مفكرة لبشرة المغربية.",
    "as.authorityTitle": "مصنوع بأمان تام",
    "as.authorityBody": "تركيبات مجرّبة تحت مراقبة ديرماتولوجية، بلا بارابان ولا سولفات. مفكرة لبشرة المغربية، حتى الحساسة. VelvaStretch™ بلا ريتينول — يعني آمن فالحمل وبعد الرضاعة.",
    "as.halalTitle": "حلال وفيجان معتمد",
    "as.halalBody": "كولاجين بحري (حوت)، باز پكتين نباتي بلا جيلاتين حيواني. معتمد حلال وفيجان — حيت عندك، اللي داز فالجلد عندو نفس القيمة ديال اللي داز فالمكلة.",
    "as.guaranteeTitle": "ضمان 4 سيمان",
    "as.guaranteeBody": "جربي، وشوفي. إلا ماقنعتيش من بعد 4 سيمان ديال الاستعمال بانتظام، كنرجعو ليك الفلوس — بلا نقاش، بلا ما ترجّعي المنتوج.",
    "as.codTitle": "الخلاص عند الاستلام",
    "as.codBody": "ماتخلصيش والو مقدّم. الشحنة توصلك فـ 24–48 ساعة فكل المغرب، وما تخلصيش غير ملي توصل. بلا خطر، بلا تقديم.",
    "as.codTrust": "الثقة قبل كل شيء",

    "cart.title": "السلة",
    "cart.empty": "السلة ديالك فاضحة",
    "cart.emptyCta": "اكتشري منتجاتنا",
    "cart.youMayLike": "💡 غتعجبك حتى (بنفس الثمن الأصلي) :",
    "cart.subtotal": "المجموع",
    "cart.checkout": "كمندي",
    "cart.freeShip": "التوصيل بالخاوة داخل",

    "co.title": "كملّي الطلب",
    "co.name": "الاسم الكامل",
    "co.namePh": "مثال: سميرة بنعلي",
    "co.phone": "التليفون",
    "co.phonePh": "0X XX XX XX XX",
    "co.address": "عنوان التوصيل",
    "co.addressPh": "الزنقة، الحومة، الرقم…",
    "co.city": "المدينة",
    "co.cityPh": "الدار البيضاء",
    "co.notes": "ملاحظات (اختياري)",
    "co.notesPh": "علامة، الطابق…",
    "co.cod": "الخلاص عند الاستلام",
    "co.codNote": "ماتخلصيش دابا والو. الموزّع كيجمع الفلوس عند الاستلام.",
    "co.submit": "أكّدي الطلب",
    "co.processing": "كايتجهز…",
    "co.summary": "ملخص الطلب",
    "co.success": "الطلب تأكّد !",
    "co.successBody": "مرسي ! الفريق ديالنا غيطيح ليك دغيا للتأكيد. الخلاص عند الاستلام.",
    "co.error": "طرا شي خطأ. عاودي مرة أخرى.",
    "co.close": "سدّي",
    "co.nameReq": "الاسم ضروري",
    "co.phoneReq": "رقم مغربي غير صالح. مثال: 0612345678",
    "co.cityReq": "المدينة ضرورية",
    "co.secure": "🔒 المعلومات ديالك محمية · ⚡ 47 مرا كيشوفو",
    "co.back": "رجع",
    "co.errorMorocco": "سمح لينا، الطلبات غير للمغرب 🇲🇦.",
    "co.errorPhone": "رقم مغربي غير صالح. مثال: 0612345678",
    "co.errorBlocked": "الولوج ممنوع من هاد الشبكة.",
    "co.errorGeneric": "طرا شي خطأ. عاودي مرة أخرى.",
    "co.upsellBody": "الجمال من الداخل + من لبراني. مع بعض، كتوفّري 49 MAD.",
    "co.upsellBoth": "عندك الدو كامل 🌹 — كنهاديو ليك −{discount} MAD على الطلب ديالك.",
    "co.upsellSave": "كترشدي {discount} MAD · كيغبر فـ {sec} ثانية",
    "co.upsellAdd": "زيدي {name} · −{discount} MAD",
    "co.upsellApply": "طبّقي −{discount} MAD",
    "co.upsellNo": "لا عافاك",

    "footer.badge": "🇲🇦 مصنوع فالمغرب",
    "footer.copy": "© 2026 Warda Beauté — wardabeaute.com | 🇲🇦 الدار البيضاء، المغرب | الخلاص 100% عند الاستلام",

    "cmp.velvastretch.vs": "مقارنة مع الكريمات والزيوت العادية ديال الصيدلية",
    "cmp.silkstop.vs": "مقارنة مع الكريمات الكيميائية ديال الإبيلاسيون",
    "cmp.collaglow.vs": "مقارنة مع كريم الكولاجين",
    "cmp.kit-collagene.vs": "مقارنة مع منتوج وحدو ولا الليزر",
    "cmp.criterion": "المعيار",
    "cmp.alt": "البديل",
    "ab.title": "علاش الزبونات ديالنا كيثقو فينا",
    "ab.sub": "ماركة مغربية، مفكرة للبشرة المتوسطية.",
    "ab.safeTitle": "مركّب بأمان تام",
    "ab.safeBody": "تركيبات مجرّبة تحت المراقبة ديال الديرماتولوجي، بلا بارابين ولا سولفات. مفكرة للبشرة المتوسطية، حتى الحساسة. VelvaStretch™ بلا retinol — يعني آمن فالحمل و من بعدو.",
    "ab.halalTitle": "حلال وفيجان مزكّى",
    "ab.halalBody": "كولاجين بحري (حوت)، قاعدة بكتين نباتي بلا جلاتين حيواني. مزكّى halal & vegan — حيت عندك، اللي كيدخل للجلد كيهمّ بقد ما اللي كيدخل للماكلة.",
    "ab.guaranteeTitle": "ضمان 4 سيمان",
    "ab.guaranteeBody": "جربي وشوفي. كان ما عجبكش من بعد 4 سيمان ديال الاستعمال المنتظم، كنرجعو الفلوس — بلا نقاش، بلا رجوع معقد.",
    "ab.codTitle": "الخلاص عند الاستلام",
    "ab.codBody": "ما كتخلصيش قبل. الكولي يوصلك فـ 24 لـ 48 ساعة فكل المغرب، وكتخلصي غير كيف يوصلك. بلا خطر، بلا فلوس لقدام.",
    "ab.trust": "الثقة قبل كل شي",

    "collection.title": "منتجاتنا",
    "collection.sub": "ثلاثة دوايات مفكرة لبشرة المغربية.",
    "faqPage.title": "أسئلة كثيرة",
    "faqPage.sub": "كلشي بغيتي تعرفي قبل ما تكمندي.",
    "story.title": "قصتنا",
    "story.sub": "كيفاش كوزينة فالدار البيضاء ولّات ماركة.",
    "story.p1": "Warda Beauté تولدات من ملاحظة بسيطة: المغربيات يستاهلو منتوجات خدامين، مصنوعين هونا، بأثمنة عادلة. بلا استيراد، بلا وسيط. غير العلم والمكونات اللي جلدك محتاجها.",
    "story.p2": "🇲🇦 مصنوع فالمغرب · 🔬 مجرّب ديرماتولوجياً · 💳 الخلاص عند الاستلام · 🚚 التوصيل 24 لـ 48 ساعة",
    "story.secEyebrow": "قناعة",
    "story.secTitle": "العلم فخدمة المرا المغربية",
    "story.sec1": "تلاتة ديال المنتوجات. تلاتة ديال الجوابات لثلاثة مشاكل حقيقية: علامات التمدد، رجوع الشعر، وفقدان الكولاجين.",
    "story.sec2": "بلا كتالوج بلا نهاية. بلا تسويق فارغ. غير الفعالية — توصلك لدارك، وتخلصي كيف توصلك.",
    "story.quote": "وردة بيوتي ماشي غير ماركة — هي الجواب ديالك",
    "contact.title": "تواصلي معانا",
    "contact.sub": "واتساب، إيمايل ولا ريسو — كن جاوبو بسرعة.",
    "contact.whatsapp": "واتساب — جواب سريع",
    "contact.instagram": "إنستغرام: @wardabeaute",
    "contact.tiktok": "تيك توك: @wardabeaute",
    "contact.email": "إيمايل: hello@wardabeaute.com",
    "contact.address": "الدار البيضاء، المغرب",
    "returnPage.title": "التوصيل والرجوع",
    "returnPage.sub": "كلشي على التوصيل، والخلاص عند الاستلام، والرجوع.",
    "privacy.title": "سياسة الخصوصية",
    "notFound.title": "الصفحة مابانتش",
    "notFound.sub": "هادي الصفحة مكتوجدش ولا مبقاتش.",
    "notFound.cta": "رجعي للرئيسية",
    "confirm.title": "مرسي على الطلب ديالك !",
    "home.heroEyebrow": "✦ ماركة مغربية · 100% طبيعي · خلصي كيف يوصلك ✦",
    "home.heroH1": "الجمال الأصيل، تولد هنا فالمغرب",
    "home.heroAr": "جمالك يستاهل الأحسن — مصنوعة هنا، لبشرتك أنتِ",
    "home.discover": "اكتشري منتجاتنا",
    "home.story": "قصتنا",
    "home.heroFooter": "🚚 التوصيل بلا فلوس · 💳 خلصي كيف يوصلك · ↩️ رجوع 30 يوم",
    "home.problemTitle": "كاع كتعرفين هاد الإحساس، أ؟",
    "home.problemBody": "إحساس التخبية ديال الكرش فالحامي. رداد الجلابة ديال الصيف. الهروب من المرايا من بعد الحمل، ولا كتشوفي بشرتك راحت منها القوة فـ 30 عام. جربتي الزيوت، جربتي الكريمات، جربتي الليزر — وكنتي كتستنايا.",
    "home.problemMicro": "كلشي جربتي، والنتيجة؟ لا شيء.",
    "home.storyEyebrow": "قصتنا",
    "home.storyTitle": "تولدات من قناعة مغربية",
    "home.story1": "Warda Beauté تولدات فواحد الكوزينة فالدار البيضاء. المؤسِسة ديالها كانت كتبغي حل لعلامات التمدد من بعد الحمل، وما كانت تلقى غير منتوجات مستوردة غالية ولا بلا شفافية.",
    "home.story2": "صاغت حلولها بوحدها — بـ مكونات مغربية، مجرّبة على جلدها، وجلد صاحباتها، وختها، ووالدتها.",
    "home.storyQuote": "هدفنا واحد — كل مرا مغربية تحس بجمالها بدون ما تخبي جسمها",
    "home.featuredEyebrow": "منتجاتنا",
    "home.featuredTitle": "تلاتة ديال الحلول. هدف واحد: تحسي بجمالك.",
    "home.scienceEyebrow": "العلم، ماشي التسويق",
    "home.scienceTitle": "علاش النشيطات ديالنا مختلفين",
    "home.sci1t": "Centella Asiatica",
    "home.sci1d": "أكثر مكون مدروس ضد علامات التمدد: الدراسات كتبين بلي كيحفّز إنتاج الكولاجين من نوع I فالدرم.",
    "home.sci2t": "كولاجين بحري محلّل",
    "home.sci2d": "مقطّع لبيبتيدات صغار، كيتشرب من الكرش ومن بعد كيوصل للجلد — أنشط صورة (عكس الكريم اللي الجزيء ديالو ما كيعدّش الجلد).",
    "home.sci3t": "الفيتامين C (Acérola)",
    "home.sci3d": "المساعد اللازم باش جسمك يصنع الكولاجين. بلاو، البيبتيدات ما كيتحوّلوش.",
    "home.bundleTitle": "الدوو Collagène — Kit Collagène Inside & Outside",
    "home.bundleSub": "VelvaStretch™ + CollaGlow™ : لخارج ولداخل، مجتمعين باش تشوفي النتائج.",
    "home.bundleCta": "اكتشري Kit Collagène",
    "home.howTitle": "كيفاش الكمندي؟ ساهل.",
    "home.how1t": "اختياري منتوجك",
    "home.how1d": "اختاري منتوجك. بلا كونط، بلا كارت.",
    "home.how2t": "خليوي كوردوني",
    "home.how2d": "السمية + تليفون. كنعيطو ليك باش نأكدو.",
    "home.how3t": "استنايا وخلاص",
    "home.how3d": "كيتوصلك فـ 24 لـ 48 ساعة. كتخلصي كاش للبوستا.",
    "home.socialSuffix": " مرأة مغربية راضية",
    "home.whyTitle": "علاش الآلاف ديال المغربيات كيثقو فينا؟",
    "home.why1t": "100% مكونات طبيعية",
    "home.why1d": "كل تركيبة مبنية على مكونات كتعرفينهم.",
    "home.why2t": "مصنوع فالمغرب",
    "home.why2d": "مركّب ومصنوع فالمغرب. بلا حتى وسيط.",
    "home.why3t": "مجرّب ديرماتولوجياً",
    "home.why3d": "تركيبات مجرّبة على البشرة المغربية الحساسة.",
    "home.why4t": "الخلاص عند الاستلام",
    "home.why4d": "ما كتخلصي غير كيف يوصلك. بلا خطر.",
    "home.why5t": "التوصيل فـ 24 لـ 48 ساعة",
    "home.why5d": "كنوصّلو فكل المغرب.",
    "home.why6t": "ضمان 4 سيمان",
    "home.why6d": "النتائج ما باينينش؟ كنرجعو الفلوس.",
    "home.finalTitle": "أنتِ تستحقي — ابدأي اليوم",
    "home.finalBody": "كل نهار كتستنايا فيه، نهار زايد تخبي فيه جسمك. Warda Beauté كاينة، مركّبة ليك، توصلك لدارك، وكتخلصي غير كيف توصلك.",
    "home.finalCta1": "اكتشري منتجاتنا",
    "home.finalCta2": "شوفي Kit Collagène",
  },
};

export type UIKey = keyof typeof ui.fr;

export function t(lang: Lang, key: string): string {
  return (lang === "ar" ? ui.ar : ui.fr)[key] ?? ui.fr[key] ?? key;
}
